-- MySQL Script generated by MySQL Workbench
-- Tue Oct 10 12:15:25 2017
-- Model: New Model Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET SQL_MODE='ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sample
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sample` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
USE `sample` ;

-- -----------------------------------------------------
-- Table `sample`.`demo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sample`.`demo` (
  `id` VARCHAR(36) NOT NULL COMMENT 'ID',
  `input` TEXT NOT NULL COMMENT '入力',
  `output` TEXT NOT NULL COMMENT '出力',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,  
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
